# -*- coding: utf-8 -*-
"""Hangman Game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qElwi53Ou3I_SqNAAWo7LRihSbqi21vq
"""

import random

lista_verbos = ['run', 'play', 'help', 'compete', 'complete', 'read', 'learn', 'teach', 'climb', 'surpass',
                'choose', 'flee', 'fight', 'combat', 'jump', 'inherit', 'pollute', 'hide', 'wash', 'drain',
                'steal', 'prig', 'crib', 'copy', 'push', 'threaten', 'pinfold', 'show', 'roar', 'order']
lista_substantivos = ['object', 'table', 'chair', 'mountain', 'city', 'earthquake', 'continent', 'river', 'player', 'teacher',
                      'thing', 'computer', 'monitor', 'keyboard', 'telephone', 'clock', 'calendar', 'idea', 'key', 'medicine',
                      'box', 'chest', 'floor', 'cork', 'wine', 'drink', 'addiction', 'mistake', 'highway', 'rotation']
lista_adjetivos = ['handsome', 'fool', 'boring', 'old', 'new', 'coll', 'fun', 'wet', 'dry', 'irritating',
                   'stupid', 'imbecile', 'insane', 'crazy', 'addicted', 'confused', 'dizzy', 'mad', 'angry', 'tired',
                   'rough', 'rude', 'thick', 'kind', 'happy', 'polite', 'cheerful', 'soaked', 'sweaty', 'exhausted']
lista_letras_encontradas = []
lista_letras_erradas = []
lista_palavra_escondida = []
num_max_erros_letras = 6
opcao1 = '1'
opcao2 = '2'
resultado_chute = None
palavra_completada = False

# JOIN THE LISTS OF VERBS, NOUNS AND ADJECTIVES AND DRAW A WORD
def sortear_palavra(a, b, c):
  nova_lista = a + b + c
  random.shuffle(nova_lista)
  palavra_sorteada = random.choice(nova_lista)

  return palavra_sorteada.upper()

# VERIFIES THE AMOUNT OF CHARACTERS WHEN CHOOSING THE OPTION TO TYPE A LETTER
def verificar_quantidade_caracteres(d):
  limite_caracteres = 1

  if(len(d) > 1):
    status = True
  else:
    status = False

  return status

# VERIFIES IF THE USER TYPED JUST LETTERS WHEN CHOOSING THE OPTION TO TYPE A LETTER
def verificar_somente_letras(e):
  range_ord_min = 65
  range_ord_max = 90
  in_range = None

  if(ord(e) in range(range_ord_min, range_ord_max + 1)):
    in_range = True
  else:
    in_range = False

  return in_range

# VERIFIES IF THE TYPED LETTER WAS ALREADY USED BY THE USER, REGARDLESS OF WHETHER IT'S RIGHT OR WRONG,
# WHEN CHOOSING THE OPTION TO TYPE A LETTER
def verificar_letra_usada(f, g, h):
  usada_encontrada = usada_errada = None

  if((f in g) and (f in h)):
    usada_encontrada = True
    usada_errada = True
  elif((f in g) and (f not in h)):
    usada_encontrada = True
    usada_errada = False
  elif((f not in g) and (f in h)):
    usada_encontrada = False
    usada_errada = True
  else:
    usada_encontrada = False
    usada_errada = False

  return usada_encontrada, usada_errada

# VERIFIES IF THE TYPED LETTER BY THE USER IS OR ISN'T IN THE DRAW WORD
def verificar_letra_palavra_sorteada(i, j):
  encontrada = None

  if(j in i):
    encontrada = True
  else:
    encontrada = False

  return encontrada

# VERIFIES IN WHICH POSITION OF THE WORD IS THE TYPED LETTER BY THE USER
def verificar_letra_posicao(k, l, m):

  for letras_palavra_sorteada in range(len(k)):
    for letra_user in l:
      if(k[letras_palavra_sorteada] == letra_user):
        m[letras_palavra_sorteada] = letra_user
      else:
        continue

  return m

# BUILDS THE GALLOW, BASED ON THE NUMBERS OF MISTAKES MADE BY THE USER
def construir_forca(n):
  parte_forca1 = parte_forca2 = parte_forca3 = ''

  if(n <= 5):
    parte_forca1 = '|         (_)'
  else:
    parte_forca1 = '|'
  if(n == 4):
    parte_forca2 = '|          |\n|          |'
  elif(n == 3):
    parte_forca2 = '|         /|\n|        / |'
  elif(n <= 2):
    parte_forca2 = '|         /|\\\n|        / | \\'
  else:
    parte_forca2 = '|\n|'
  if(n == 1):
    parte_forca3 = '|         /\n|        /'
  elif(n == 0):
    parte_forca3 = '|         / \\\n|        /   \\'
  else:
    parte_forca3 = '|'

  return parte_forca1, parte_forca2, parte_forca3

if __name__ == '__main__':
  print('Welcome user!')
  print('This program is a Hangman Game!')
  print(f'If you wish to try just by letters, you can make up to {num_max_erros_letras} mistakes!')
  print('If you wish to try to guess the right word, you only have ONE try!')

  nova_palavra = sortear_palavra(lista_verbos, lista_substantivos, lista_adjetivos)

  # CREATES A NEW LIST WITH THE SAME AMOUNT OF CHARACTERS AS THE DRAW WORD,
  # REPLACING EACH LETTER WITH "_"
  for letras_palavra in nova_palavra:
        letras_palavra = '_'
        lista_palavra_escondida.append(letras_palavra)

  while(True):
    forca1, forca2, forca3 = construir_forca(num_max_erros_letras)

    print('____________')
    print('|          |')
    print(forca1)
    print(forca2)
    print(forca3)

    # PRINTS IN THE SCREEN THE POSITIONS OF EACH LETTER FROM THE DAR WORD WITH "_" AND,
    # IF THE USER FINDS A LETTER, IT WILL BE REPLACED THE "_"
    lista_posicoes = verificar_letra_posicao(nova_palavra, lista_letras_encontradas, lista_palavra_escondida)
    print(' '.join(lista_posicoes))

    # IF THE USER TRY TO GUESS A WRONG LETTER, IT WILL BE PRINTED ON THE SCREEN
    if(len(lista_letras_erradas) > 0):
      print('Used letters:', end = ' ')
      print(' '.join(lista_letras_erradas))

    # WHILE THE USER HAVE REMAINING ATTEMPTS, THE PROGRAM WILL COMPARE IF
    # ALL THE LETTERS THE USER GUESSED RIGHT COMPLETE THE DRAW WORD.
    # IF THAT'S THE CASE, THE "WHILE" LOOP WILL STOP HERE
    if(num_max_erros_letras > 0):
      if(''.join(lista_posicoes) == nova_palavra):
        palavra_completada = True
        break

      print('-' * 30)
      print(f'Remaining mistakes: {num_max_erros_letras}')
      print('You wish:')
      print(f'{opcao1} - Choose a letter\n{opcao2} - Try to guess the word')
      print('Please, choose one of these options!')
      escolha_user = input()
      print('-' * 30)

      if(escolha_user == opcao1):
        while(True):
          print('Which letter you wish to see if is in the draw word?')
          letra_user = input()
          print('-' * 30)

          letra_user = letra_user.upper()
          acima_limite_caractere = verificar_quantidade_caracteres(letra_user)

          if(len(letra_user) == 0):
            print("Error! You didn't typed anything!")
          else:
            if(acima_limite_caractere == True):
              print('Error! You can type just one letter!')
            else:
              somente_letra = verificar_somente_letras(letra_user)

              if(somente_letra == False):
                print("Error! You didn't typed a letter!")
              else:
                letra_usada_encontrada, letra_usada_errada = verificar_letra_usada(letra_user, lista_letras_encontradas, lista_letras_erradas)

                if((letra_usada_encontrada == True) or (letra_usada_errada == True)):
                  print("Error! You already used that letter!")
                else:
                  letra_encontrada = verificar_letra_palavra_sorteada(nova_palavra, letra_user)

                  if(letra_encontrada == True):
                    # IF THE TYPED LETTER IS IN THE DRAW WORD, IT WILL BE ADDED TO THE LIST OF RIGHT LETTERS
                    lista_letras_encontradas.append(letra_user)
                  else:
                    # IF THE TYPED LETTER IS NOT IN THE DRAW WOR, IT WILL BE ADDED TO THE LIST OF
                    # WRONG LETTERS AND DECREASE THE NUMBER OF MISTAKES YOU CAN STILL MAKE
                    lista_letras_erradas.append(letra_user)
                    num_max_erros_letras -= 1
                  break
          print('Please, try again!')
          print('-' * 30)
      elif(escolha_user == opcao2):
        while(True):
          print('What is the right word?')
          chute_user = input()

          if(len(chute_user) == 0):
            print("Error! You didn't typed anything!")
            print('Please, try again!')
            print('-' * 30)
          else:
            if(chute_user.upper() == nova_palavra):
              resultado_chute = True
            else:
              resultado_chute = False
            break
        break
      else:
        print("Error! You didn't typed one of the available options!")
        print('Please, try again!')
        print('-' * 30)
    else:
      # WHEN THE CHANCES TO MAKE MISTAKES RUN OUT, THE FIRST "WHILE" LOOP STOPS HERE
      break

  print('-' * 30)
  if(num_max_erros_letras == 0):
    print('Your attempts are over!')
  elif((resultado_chute == True) or (palavra_completada == True)):
    print('Congratulations! You got it right!')
  else:
    print('You got it wrong!')

  print(f'The word was: {nova_palavra}')
  print('GAME OVER!')
  print('-' * 30)